/*
 * Copyright 2025 Dakkshesh <beakthoven@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package io.github.beakthoven.TrickyStoreOSS.interceptors

import android.annotation.SuppressLint
import android.hardware.security.keymint.SecurityLevel
import android.os.IBinder
import android.os.Parcel
import android.system.keystore2.IKeystoreService
import android.system.keystore2.KeyDescriptor
import android.system.keystore2.KeyEntryResponse
import io.github.beakthoven.TrickyStoreOSS.CertificateHack
import io.github.beakthoven.TrickyStoreOSS.CertificateUtils
import io.github.beakthoven.TrickyStoreOSS.KeyBoxUtils
import io.github.beakthoven.TrickyStoreOSS.config.PkgConfig
import io.github.beakthoven.TrickyStoreOSS.interceptors.InterceptorUtils.createTypedObjectReply
import io.github.beakthoven.TrickyStoreOSS.interceptors.InterceptorUtils.getTransactCode
import io.github.beakthoven.TrickyStoreOSS.interceptors.InterceptorUtils.hasException
import io.github.beakthoven.TrickyStoreOSS.logging.Logger
import io.github.beakthoven.TrickyStoreOSS.putCertificateChain
import java.util.concurrent.ConcurrentHashMap

@SuppressLint("BlockedPrivateApi")
object Keystore2Interceptor : BaseKeystoreInterceptor() {
    private val getKeyEntryTransaction =
        getTransactCode(IKeystoreService.Stub::class.java, "getKeyEntry")
    private val deleteKeyTransaction =
        getTransactCode(IKeystoreService.Stub::class.java, "deleteKey")
    private val grantTransaction =
        getTransactCode(IKeystoreService.Stub::class.java, "grant")

    /**
     * Grant IDs (nspace values in GRANT-domain KeyDescriptors) for keys whose alias
     * was generated by a needHack app (tracked via SecurityLevelInterceptor.generatedAliases).
     *
     * When such a key is granted to another UID, getKeyEntry(GRANT) would either:
     *  (a) call hackCertificateChain again → different DER → SELF/ISOLATED_CHAIN_SPLIT
     *  (b) miss the cert cache (pure SIGN key) → skip+real cert path conflicts with owner path
     *
     * By blocking grant-based getKeyEntry for these IDs (KEY_NOT_FOUND), Duck Detector's
     * Grant self-domain and Grant isolated-domain probes report UNAVAILABLE instead of
     * CHAIN_SPLIT, matching official TrickyStore behavior.
     *
     * Uses ConcurrentHashMap.newKeySet for proper Long-keyed concurrency (avoids erasure
     * ambiguity that Collections.newSetFromMap can have with Kotlin type inference).
     */
    private val blockedGrantIds = ConcurrentHashMap.newKeySet<Long>()

    override val serviceName = "android.system.keystore2.IKeystoreService/default"
    override val processName = "keystore2"
    override val injectionCommand = "exec ./inject `pidof keystore2` libShieldAttestation.so entry"

    private var teeInterceptor: SecurityLevelInterceptor? = null
    private var strongBoxInterceptor: SecurityLevelInterceptor? = null
    
    override fun onInterceptorSetup(service: IBinder, backdoor: IBinder) {
        setupSecurityLevelInterceptors(service, backdoor)
    }
    
    private fun setupSecurityLevelInterceptors(service: IBinder, backdoor: IBinder) {
        val ks = IKeystoreService.Stub.asInterface(service)
        
        val tee = kotlin.runCatching { ks.getSecurityLevel(SecurityLevel.TRUSTED_ENVIRONMENT) }
            .getOrNull()
        if (tee != null) {
            Logger.i("Registering for TEE SecurityLevel: $tee")
            val interceptor = SecurityLevelInterceptor(tee, SecurityLevel.TRUSTED_ENVIRONMENT)
            registerBinderInterceptor(backdoor, tee.asBinder(), interceptor)
            teeInterceptor = interceptor
        } else {
            Logger.i("No TEE SecurityLevel found")
        }
        
        val strongBox = kotlin.runCatching { ks.getSecurityLevel(SecurityLevel.STRONGBOX) }
            .getOrNull()
        if (strongBox != null) {
            Logger.i("Registering for StrongBox SecurityLevel: $strongBox")
            val interceptor = SecurityLevelInterceptor(strongBox, SecurityLevel.STRONGBOX)
            registerBinderInterceptor(backdoor, strongBox.asBinder(), interceptor)
            strongBoxInterceptor = interceptor
        } else {
            Logger.i("No StrongBox SecurityLevel found")
        }
    }

    private fun isIsolatedUid(uid: Int): Boolean = (uid % 100000) >= 90000

    /**
     * Build a ServiceSpecificException(KEY_NOT_FOUND) reply without using
     * android.os.ServiceSpecificException directly (available only in API ≥ 35 for
     * public use; avoid compile-time dependency).  The Parcel format is:
     *   int  -8   (EX_SERVICE_SPECIFIC)
     *   String    (message, nullable → null here)
     *   int   7   (KEY_NOT_FOUND keystore2 error code)
     */
    private fun keyNotFoundReply(): OverrideReply {
        val p = Parcel.obtain()
        p.writeInt(-8)        // EX_SERVICE_SPECIFIC
        p.writeString(null)   // message
        p.writeInt(7)         // ResponseCode::KEY_NOT_FOUND
        return OverrideReply(0, p)
    }

    override fun onPreTransact(
        target: IBinder,
        code: Int,
        flags: Int,
        callingUid: Int,
        callingPid: Int,
        data: Parcel
    ): Result {
        // getKeyEntry: handle BEFORE the isIsolatedUid gate so that blocked GRANT IDs
        // are rejected for BOTH non-isolated and isolated callers.
        if (code == getKeyEntryTransaction && KeyBoxUtils.hasKeyboxes()) {
            Logger.d("intercept pre  $target uid=$callingUid pid=$callingPid dataSz=${data.dataSize()}")
            try {
                data.enforceInterface(IKeystoreService.DESCRIPTOR)
                val descriptor = data.readTypedObject(KeyDescriptor.CREATOR) ?: return Skip

                // Block GRANT-domain access for tracked grant IDs.
                // These are grants issued for cert-hacked SIGN+challenge keys; letting them
                // through would cause hackCertificateChain to run again (non-deterministic
                // timestamp) and produce a different DER → SELF/ISOLATED_CHAIN_SPLIT.
                if (descriptor.domain == 2 /* GRANT */ && blockedGrantIds.contains(descriptor.nspace)) {
                    Logger.i("Blocked GRANT nspace=${descriptor.nspace} uid=$callingUid (isolated=${isIsolatedUid(callingUid)})")
                    return keyNotFoundReply()
                }

                // Standard isolated-UID gate: beyond the GRANT check above, isolated processes
                // must not hit the alias cache (cache is keyed by uid+alias; isolated UIDs are
                // ephemeral, so a miss would return a null response and crash the caller).
                if (isIsolatedUid(callingUid)) return Skip

                if (PkgConfig.needGenerate(callingUid)) {
                    val response = SecurityLevelInterceptor.getKeyResponse(callingUid, descriptor.alias)
                    if (response != null) {
                        Logger.i("Found generated response for uid=$callingUid alias=${descriptor.alias}")
                        return createTypedObjectReply(response)
                    } else {
                        Logger.e("No generated response found for uid=$callingUid alias=${descriptor.alias}")
                        val nullParcel = Parcel.obtain()
                        nullParcel.writeTypedObject(null as KeyEntryResponse?, 0)
                        return OverrideReply(0, nullParcel)
                    }
                } else if (PkgConfig.needHack(callingUid)) {
                    if (SecurityLevelInterceptor.shouldSkipLeafHack(callingUid, descriptor.alias)) {
                        Logger.i("skip leaf hack for uid=$callingUid alias=${descriptor.alias}")
                        val response = SecurityLevelInterceptor.getKeyResponse(callingUid, descriptor.alias)
                        if (response != null) {
                            Logger.i("Found generated response for uid=$callingUid alias=${descriptor.alias}")
                            return createTypedObjectReply(response)
                        } else {
                            Logger.e("No generated response found for uid=$callingUid alias=${descriptor.alias}")
                            val nullParcel = Parcel.obtain()
                            nullParcel.writeTypedObject(null as KeyEntryResponse?, 0)
                            return OverrideReply(0, nullParcel)
                        }
                    } else {
                        Logger.i("proceeding with leaf hack for uid=$callingUid alias=${descriptor.alias}")
                        return Continue
                    }
                }
                return Skip
            } catch (e: Exception) {
                Logger.e("Exception in onPreTransact uid=$callingUid pid=$callingPid!", e)
                return Skip
            }
        }

        // For all other transaction codes, skip isolated UIDs entirely.
        if (isIsolatedUid(callingUid)) return Skip

        return Skip
    }

    override fun onPostTransact(
        target: IBinder,
        code: Int,
        flags: Int,
        callingUid: Int,
        callingPid: Int,
        data: Parcel,
        reply: Parcel?,
        resultCode: Int
    ): Result {
        if (target != keystore || reply == null) return Skip
        if (reply.hasException()) return Skip
        val p = Parcel.obtain()
        Logger.d("intercept post $target uid=$callingUid pid=$callingPid dataSz=${data.dataSize()} replySz=${reply.dataSize()}")

        if (code == deleteKeyTransaction && resultCode == 0) {
            data.enforceInterface("android.system.keystore2.IKeystoreService")

            val keyDescriptor = data.readTypedObject(KeyDescriptor.CREATOR)
            if (keyDescriptor == null || keyDescriptor.domain == 0) return Skip

            val cacheKey = SecurityLevelInterceptor.Key(callingUid, keyDescriptor.alias)
            SecurityLevelInterceptor.keys.remove(cacheKey)
            SecurityLevelInterceptor.hackedCertCache.remove(cacheKey)
            SecurityLevelInterceptor.generatedAliases.remove(cacheKey)

            return Skip
        } else if (code == grantTransaction) {
            // Record the nspace of successfully-granted keys that were generated by a needHack
            // app (i.e. alias is in generatedAliases) so that grant-based getKeyEntry calls
            // are blocked (UNAVAILABLE → KEY_NOT_FOUND) in onPreTransact.
            //
            // We check BOTH hackedCertCache (attested keys where we hacked the cert) AND
            // generatedAliases (all aliases created by the UID, including pure SIGN keys
            // whose cert wasn't cached). This prevents SELF/ISOLATED_CHAIN_SPLIT for all paths.
            if (PkgConfig.needHack(callingUid) || PkgConfig.needGenerate(callingUid)) {
                try {
                    data.enforceInterface("android.system.keystore2.IKeystoreService")
                    val keyDescriptor = data.readTypedObject(KeyDescriptor.CREATOR)
                    val alias = keyDescriptor?.alias
                    if (alias != null) {
                        val cacheKey = SecurityLevelInterceptor.Key(callingUid, alias)
                        val isTracked = SecurityLevelInterceptor.hackedCertCache.containsKey(cacheKey) ||
                                SecurityLevelInterceptor.generatedAliases.contains(cacheKey)
                        if (isTracked) {
                            val grantDescriptor = reply.readTypedObject(KeyDescriptor.CREATOR)
                            if (grantDescriptor?.domain == 2) {
                                blockedGrantIds.add(grantDescriptor.nspace)
                                Logger.i("Tracked GRANT nspace=${grantDescriptor.nspace} alias=$alias uid=$callingUid")
                            }
                        }
                    }
                } catch (e: Exception) {
                    Logger.e("grantTransaction onPostTransact failed uid=$callingUid", e)
                }
            }
            return Skip
        } else if (code == getKeyEntryTransaction) {
            // Spoof certs for:
            //   • target apps (needHack/needGenerate) — keybox cert needed for STRONG integrity
            //   • isolated processes (uid % 100000 >= 90000) — GMS attestation worker runs in an
            //     isolated process whose UID is NOT in PkgConfig; it still needs the keybox cert
            //     from getKeyEntry so Play Integrity returns STRONG, not BASIC.
            //
            // For target apps in AUTO mode (e.g. Duck Detector) the primary path is the cert
            // cache: SecurityLevelInterceptor.onPostTransact hacked generateKey and stored the
            // cert; we return that SAME cert here so Duck Detector's Patch-mode / Binder-chain
            // probes see generateKey == getKeyEntry (hackCertificateChain is non-deterministic —
            // a fresh call produces different DER bytes even for the same key, causing the mismatch).
            if (!PkgConfig.needHack(callingUid) && !PkgConfig.needGenerate(callingUid) && !isIsolatedUid(callingUid)) return Skip
            try {
                data.enforceInterface("android.system.keystore2.IKeystoreService")
                val reqDescriptor = data.readTypedObject(KeyDescriptor.CREATOR)
                val alias = reqDescriptor?.alias
                val response = reply.readTypedObject(KeyEntryResponse.CREATOR)
                if (response != null) {
                    // Cache-hit path: return the cert that was produced by generateKey so both
                    // calls return byte-for-byte identical DER → Duck Detector sees no leaf mismatch.
                    val cached = if (alias != null)
                        SecurityLevelInterceptor.hackedCertCache[SecurityLevelInterceptor.Key(callingUid, alias)]
                    else null
                    if (cached != null) {
                        response.metadata?.let { meta ->
                            meta.certificate = cached.first
                            meta.certificateChain = cached.second
                        }
                        Logger.i("getKeyEntry: cert cache hit uid=$callingUid alias=$alias")
                        return createTypedObjectReply(response)
                    }
                    // Cache-miss path.
                    //
                    // If this alias was generated by this UID (tracked in generatedAliases), the
                    // TEE cert is already in the real keystore2 reply unchanged — both generateKey
                    // and this getKeyEntry hit the real TEE → cert is byte-for-byte identical.
                    // Calling hackCertificateChain here would produce a *different* cert (fresh
                    // timestamp/signature) and break Patch mode / Binder chain probes.
                    // Return Skip to let the caller receive the real, consistent TEE cert.
                    if (alias != null && SecurityLevelInterceptor.generatedAliases
                            .contains(SecurityLevelInterceptor.Key(callingUid, alias))) {
                        Logger.i("getKeyEntry: generated alias, no cache → passthrough real cert uid=$callingUid alias=$alias")
                        p.recycle()
                        return Skip
                    }
                    // Not a generated alias → isolated GMS process with pre-provisioned key
                    // (or some other path). Apply hackCertificateChain for STRONG integrity.
                    val chain = CertificateUtils.run { response.getCertificateChain() }
                    if (chain != null) {
                        val newChain = CertificateHack.hackCertificateChain(chain)
                        response.putCertificateChain(newChain).getOrThrow()
                        Logger.i("Hacked certificate for uid=$callingUid")
                        return createTypedObjectReply(response)
                    } else {
                        p.recycle()
                    }
                } else {
                    p.recycle()
                }
            } catch (t: Throwable) {
                Logger.e("failed to hack certificate chain of uid=$callingUid pid=$callingPid!", t)
                p.recycle()
            }
        }
        return Skip
    }
}
